<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>Detail - Gunung Bromo Deskripsi</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>4b3d00ed-27fe-4130-a6cc-c508a41c3e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7294c7a7-118d-427b-8106-0bd27a915aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Gunung Bromo adalah gunung api yang masih aktif yang terletak di Jawa Timur tepatnya di Kabupaten Probolinggo, Pasuruan, Lumajang, dan Kabupaten Malang. Gunung Bromo memiliki ketinggian 2.392 mdpl.
     Sejarah terbentuknya gunung Bromo adalah bermula dari letusan yang memecah belah Gunung Tengger (4000 mdpl). Akibat letusan tersebut terbentuklah sebuah komplek gunung yang di dalamnya meliputi Lautan Pasir, Gunung Widodaren, Gunung Watangan, Gunung Kursi, Gunung Batok dan Gunung Bromo. Selain penjelasan secara ilmiah, terbentuknya atau sejarah gunung Bromo juga sangat kental akan cerita rakyat.</value>
      <webElementGuid>ddb2af70-6bd7-4e9a-ac3f-34f03987b768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>com.wahidari.pendaki:id/detail_gunung</value>
      <webElementGuid>40205c75-9ec3-4fa3-862d-8b2b5cfb2179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.wahidari.pendaki</value>
      <webElementGuid>48df588b-55db-4142-a893-cb7d89d6379b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa242d59-06b3-42d5-bb5f-f2928700b53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9aebe3bc-d22c-4349-b156-0f2dc1bcb20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d550d48-1224-463c-aaa2-879c6c3d72e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ff0fa93-6e9b-4e64-a8da-d521ae5c3ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>62ab1f0e-8529-405c-b12c-523598b1be06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3ae454b1-f2bb-4d74-99d2-decb63aab024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>72e9fae6-02a4-4a82-9097-6ecf39627bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>05dbfbb6-86f7-48d9-a0ca-57425d889d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>903c29be-7446-4138-903a-38f3df9adc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>370183cd-8f86-4b0a-b727-024c3510e92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>b50898fc-6f5a-49eb-ba05-d4f010be235c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>373</value>
      <webElementGuid>32d19063-906f-42e9-9e92-fd96a7c24766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1008</value>
      <webElementGuid>2246e5d6-2382-41cb-94df-118ad48fba68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>863</value>
      <webElementGuid>8c6fe529-90e7-4834-a111-3f79820fc098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[36,373][1044,1236]</value>
      <webElementGuid>5b076c42-6a65-4838-85e8-15cefd438881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3efef1b2-c6b3-4b31-8ab5-4da05761aa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.TextView[2]</value>
      <webElementGuid>089be916-0ee2-4671-9c86-c49448658779</webElementGuid>
   </webElementProperties>
   <locator>//*[@class = 'android.widget.TextView' and (@text = '     Gunung Bromo adalah gunung api yang masih aktif yang terletak di Jawa Timur tepatnya di Kabupaten Probolinggo, Pasuruan, Lumajang, dan Kabupaten Malang. Gunung Bromo memiliki ketinggian 2.392 mdpl.
     Sejarah terbentuknya gunung Bromo adalah bermula dari letusan yang memecah belah Gunung Tengger (4000 mdpl). Akibat letusan tersebut terbentuklah sebuah komplek gunung yang di dalamnya meliputi Lautan Pasir, Gunung Widodaren, Gunung Watangan, Gunung Kursi, Gunung Batok dan Gunung Bromo. Selain penjelasan secara ilmiah, terbentuknya atau sejarah gunung Bromo juga sangat kental akan cerita rakyat.' or . = '     Gunung Bromo adalah gunung api yang masih aktif yang terletak di Jawa Timur tepatnya di Kabupaten Probolinggo, Pasuruan, Lumajang, dan Kabupaten Malang. Gunung Bromo memiliki ketinggian 2.392 mdpl.
     Sejarah terbentuknya gunung Bromo adalah bermula dari letusan yang memecah belah Gunung Tengger (4000 mdpl). Akibat letusan tersebut terbentuklah sebuah komplek gunung yang di dalamnya meliputi Lautan Pasir, Gunung Widodaren, Gunung Watangan, Gunung Kursi, Gunung Batok dan Gunung Bromo. Selain penjelasan secara ilmiah, terbentuknya atau sejarah gunung Bromo juga sangat kental akan cerita rakyat.') and @resource-id = 'com.wahidari.pendaki:id/detail_gunung']</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
