<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>Detail - Gunung Merapi Deskripsi</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>e7993500-fe59-42d9-b043-7b913dca6a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b14e95e2-9d6b-45c3-912e-91758d963517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Gunung Merapi adalah gunung api teraktif di Indonesia. Gunung Merapi dikategorikan dalam gunung berapi tipe strato atau masih aktif. Tercatat dalam catatan modern bahwa gunung Merapi mengalami erupsi atau letusan setiap 2-5 tahun sekali. Tahun 2010 adalah pembuktian betapa ganasnya erupsi gunung Merapi di sepuluh tahun terakhir ini. Gunung Merapi tercatat sudah meletus sebanyak 68 kali sejak tahun 1548.
     Gunung Merapi selain masuk dalam kategori gunung api paling aktif juga masuk dalam kategori gunung api paling berbahaya. Karena jika gunung ini meletus maka akibatnya akan sangat fatal mengingat sekeliling gunung Merapi adalah pemukiman padat. Dari sisi barat ada kabupaten Magelang, sebelah selatan ada kabupaten Sleman dan kota Yogyakarta, dari sisi timur ada kabupaten Boyolali, dan sisi tenggara kabupaten Klaten.</value>
      <webElementGuid>382aa953-0516-44be-87e7-65789e398b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>com.wahidari.pendaki:id/detail_gunung</value>
      <webElementGuid>e56e139c-bdc5-4a32-add9-89f398a7bc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.wahidari.pendaki</value>
      <webElementGuid>b9ca2cad-329c-4b3a-bd0a-9de26b5b8a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0a45e983-4bf0-4187-82ee-b34651297bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b697b017-50ed-43e9-9055-94bd2143c2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d04bb1d2-7c3f-44fd-acd7-b6b6527b2faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b82a5aa9-8ecc-4f1a-a96f-bf9c041fdf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6481885e-8220-4904-a202-10d2a0adee39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95113bf7-1365-4465-acd5-99d0857ed73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>52e8ff3f-45c8-4762-9bfd-0beb949e9856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4db2cb8-64d0-4b36-a725-6b5ffcb37608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a46102f-3229-4e68-9525-fd8bcb3418c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e93d2087-7bed-4319-ba41-0fb5bc0171ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>6e653ee2-5a46-44fa-a7f2-cf86c8c3c275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>398</value>
      <webElementGuid>a421da00-94ab-4e6e-8452-88a954820fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1008</value>
      <webElementGuid>0c61c37f-c432-4330-8da6-987ca8dd62bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1148</value>
      <webElementGuid>08168894-fa31-49c6-a73b-48d3e0d232bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[36,398][1044,1546]</value>
      <webElementGuid>edcb2df5-e4c1-454c-9a7e-22af164ec2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2ae25eb1-9f7f-49ab-8cc4-8833c9144479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.TextView[2]</value>
      <webElementGuid>01a20e5d-d87a-40cb-840b-05d64111184b</webElementGuid>
   </webElementProperties>
   <locator>//*[@class = 'android.widget.TextView' and (@text = '     Gunung Merapi adalah gunung api teraktif di Indonesia. Gunung Merapi dikategorikan dalam gunung berapi tipe strato atau masih aktif. Tercatat dalam catatan modern bahwa gunung Merapi mengalami erupsi atau letusan setiap 2-5 tahun sekali. Tahun 2010 adalah pembuktian betapa ganasnya erupsi gunung Merapi di sepuluh tahun terakhir ini. Gunung Merapi tercatat sudah meletus sebanyak 68 kali sejak tahun 1548.
     Gunung Merapi selain masuk dalam kategori gunung api paling aktif juga masuk dalam kategori gunung api paling berbahaya. Karena jika gunung ini meletus maka akibatnya akan sangat fatal mengingat sekeliling gunung Merapi adalah pemukiman padat. Dari sisi barat ada kabupaten Magelang, sebelah selatan ada kabupaten Sleman dan kota Yogyakarta, dari sisi timur ada kabupaten Boyolali, dan sisi tenggara kabupaten Klaten.' or . = '     Gunung Merapi adalah gunung api teraktif di Indonesia. Gunung Merapi dikategorikan dalam gunung berapi tipe strato atau masih aktif. Tercatat dalam catatan modern bahwa gunung Merapi mengalami erupsi atau letusan setiap 2-5 tahun sekali. Tahun 2010 adalah pembuktian betapa ganasnya erupsi gunung Merapi di sepuluh tahun terakhir ini. Gunung Merapi tercatat sudah meletus sebanyak 68 kali sejak tahun 1548.
     Gunung Merapi selain masuk dalam kategori gunung api paling aktif juga masuk dalam kategori gunung api paling berbahaya. Karena jika gunung ini meletus maka akibatnya akan sangat fatal mengingat sekeliling gunung Merapi adalah pemukiman padat. Dari sisi barat ada kabupaten Magelang, sebelah selatan ada kabupaten Sleman dan kota Yogyakarta, dari sisi timur ada kabupaten Boyolali, dan sisi tenggara kabupaten Klaten.') and @resource-id = 'com.wahidari.pendaki:id/detail_gunung']</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
