<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>Gunung Andong - Jalur Selatan - Details</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>9376b747-8c67-49be-842f-196b8db34424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2c05edd8-2535-4050-b1ad-21b3c6a5e13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dari banyak rute untuk mendaki puncak gunung andong, jalur yang paling banyak disukai oleh wisatawan ialah jalur selatan, hal ini dikarenakan rute jalur selatan memiliki jalan yang beraspal dan bagus, selain itu juga pemandangan yang ada di jalur selatan lebih indah dibandingkan dengan jalur lainnya, perjalanan bisa dimulai dari Terminal Tidar Magelang, setelah itu anda bisa meneruskan perjalanan menuju Pasar Ngablak, dari pasar ngablak anda akan menempuh perjalanan sejauh 2 Km ke arah makam dusun kenteng, nah dari dusun kenteng inilah Basecamp Sawit sudah sangat dekat, jika anda sudah mencapai base camp sawit maka perjalanan menuju puncak gunung andong bisa dimulai.</value>
      <webElementGuid>edb45730-3b41-497a-98df-643bde64dd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.wahidari.pendaki</value>
      <webElementGuid>c768b0b5-8b22-46a9-b509-5de0a5c2b4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12f448ef-2032-4811-84ae-9a3c59327b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e1731553-9732-47c5-956b-0b47e165a593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1765ec1-c897-45f0-83e3-97639cf3ebea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e2eb425-363d-4329-85d6-7cc2cd7600a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e114ce86-ceaf-4958-befe-0a35b539e9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c237983c-b20f-4690-8443-b6dc1e5d7376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1bd06e72-c843-49a7-9b87-16e313110ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1a1090b5-20e6-4196-91c9-ab40a82f9569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>67e1f71f-bc73-44b4-8fab-f1f7311a7016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5c424f77-2646-487e-833b-7ef836f94762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>00b9e029-7187-4778-98a8-d0b9e8dd8d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>1292</value>
      <webElementGuid>01f96fa1-1495-45d3-b6d1-9c7962fbe5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1020</value>
      <webElementGuid>a8c0185e-6f8a-4b15-a165-64c6c78cb409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>484</value>
      <webElementGuid>edccf024-3bed-4230-8ce6-362474385323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[30,1292][1050,1776]</value>
      <webElementGuid>acd818e9-b720-4312-ae77-1959b53162b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0a7c599-13be-4f63-b7e3-8778077ad65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[4]/android.widget.TextView[1]</value>
      <webElementGuid>4ee394ae-cf1e-4564-8b6f-7ebc509d6d02</webElementGuid>
   </webElementProperties>
   <locator>//*[@class = 'android.widget.TextView' and (@text = 'Dari banyak rute untuk mendaki puncak gunung andong, jalur yang paling banyak disukai oleh wisatawan ialah jalur selatan, hal ini dikarenakan rute jalur selatan memiliki jalan yang beraspal dan bagus, selain itu juga pemandangan yang ada di jalur selatan lebih indah dibandingkan dengan jalur lainnya, perjalanan bisa dimulai dari Terminal Tidar Magelang, setelah itu anda bisa meneruskan perjalanan menuju Pasar Ngablak, dari pasar ngablak anda akan menempuh perjalanan sejauh 2 Km ke arah makam dusun kenteng, nah dari dusun kenteng inilah Basecamp Sawit sudah sangat dekat, jika anda sudah mencapai base camp sawit maka perjalanan menuju puncak gunung andong bisa dimulai.' or . = 'Dari banyak rute untuk mendaki puncak gunung andong, jalur yang paling banyak disukai oleh wisatawan ialah jalur selatan, hal ini dikarenakan rute jalur selatan memiliki jalan yang beraspal dan bagus, selain itu juga pemandangan yang ada di jalur selatan lebih indah dibandingkan dengan jalur lainnya, perjalanan bisa dimulai dari Terminal Tidar Magelang, setelah itu anda bisa meneruskan perjalanan menuju Pasar Ngablak, dari pasar ngablak anda akan menempuh perjalanan sejauh 2 Km ke arah makam dusun kenteng, nah dari dusun kenteng inilah Basecamp Sawit sudah sangat dekat, jika anda sudah mencapai base camp sawit maka perjalanan menuju puncak gunung andong bisa dimulai.')]</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
