<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>Gunung Andong - Jalur Barat - Details</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>0dafe681-561f-45c1-a477-6cb574d18747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>97ef2e88-1a9e-4c82-a970-f538a9e52864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jika anda datang dari wilayah barat kota magelang, maka jalur alternatif untuk mendaki puncak gunung andong bisa dimulai dari Terminal Secang, kemudian anda bisa menaiki bus ke arah Krincing dan kemudian menuju pasar Grabag, jika anda belum menyiapakan perbekalan untuk mendaki sebaiknya anda membeli perbekalan di desa grabag ini, selesai dari pasar grabag ini anda bisa menuruskan perjalanan menuju desa mangu kemudian meneruskan perjalanan ke basecamp Sawit, nah di basecamp ini pendakian menuju puncak gunung andong bisa dimulai.</value>
      <webElementGuid>7fc36d86-7ccc-4088-92fd-45fc3bc25180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.wahidari.pendaki</value>
      <webElementGuid>671cdcbe-283f-4a48-9a15-1466bc3d8773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>60d7a242-8007-4ec8-b979-f659b0ba250c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bd64fcfe-9d16-4a50-9734-4f1267b6bba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2f4109f-734e-4817-895b-94dfe72c4d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5b41393-7195-434a-9f24-08798bd5f5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6f38937-4079-462a-a376-ba02b9cf687b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ed779adb-01ac-4a75-b476-63db60a49e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>91f2b7e8-9ae8-4a43-bb6f-86bdf2d1f15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5fc01df7-a01b-49b0-bbed-c921d579bbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d63e11b9-d42f-4fdf-a1d2-4173ac5f4bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4c9aeb3-f3ff-4a1f-b605-167fdb0ffcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>9cc4b4bc-dfdf-4a7c-a471-fc834e0d4f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>432</value>
      <webElementGuid>87d74681-c821-4211-a44d-0bad110ce326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1020</value>
      <webElementGuid>5b6272f5-8cdb-4b7a-a5ea-47f7f7beee25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>644</value>
      <webElementGuid>7c98d2b8-6151-437d-8870-bb52156e87dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[30,432][1050,1076]</value>
      <webElementGuid>59a3cf4f-d607-4fcd-a164-bae30051b0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a67a5186-53f1-405a-9e50-38671e7561f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[2]/android.widget.TextView[1]</value>
      <webElementGuid>8247a621-bb0c-4530-ae95-91a5beb5087d</webElementGuid>
   </webElementProperties>
   <locator>//*[@class = 'android.widget.TextView' and (@text = 'Jika anda datang dari wilayah barat kota magelang, maka jalur alternatif untuk mendaki puncak gunung andong bisa dimulai dari Terminal Secang, kemudian anda bisa menaiki bus ke arah Krincing dan kemudian menuju pasar Grabag, jika anda belum menyiapakan perbekalan untuk mendaki sebaiknya anda membeli perbekalan di desa grabag ini, selesai dari pasar grabag ini anda bisa menuruskan perjalanan menuju desa mangu kemudian meneruskan perjalanan ke basecamp Sawit, nah di basecamp ini pendakian menuju puncak gunung andong bisa dimulai.' or . = 'Jika anda datang dari wilayah barat kota magelang, maka jalur alternatif untuk mendaki puncak gunung andong bisa dimulai dari Terminal Secang, kemudian anda bisa menaiki bus ke arah Krincing dan kemudian menuju pasar Grabag, jika anda belum menyiapakan perbekalan untuk mendaki sebaiknya anda membeli perbekalan di desa grabag ini, selesai dari pasar grabag ini anda bisa menuruskan perjalanan menuju desa mangu kemudian meneruskan perjalanan ke basecamp Sawit, nah di basecamp ini pendakian menuju puncak gunung andong bisa dimulai.')]</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
