<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>Gunung Andong - Jalur Utara - Details</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>8e364724-71dc-42de-8843-e73171f71b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8b8813f4-f22c-4023-a512-be98571313a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selain melewati jalur barat, rute alternatif dalam melakukan pendakian menuju puncak gunung andong juga bisa dimulai dari jalur utara yaitu dari semaran menuju solo kemudian transit ke pasar sapi salatgiga, nah dari sini anda bisa menuruskan perjalanan ke pasar ngablak, dari pasar ngablak anda bisa meneruskan perjalanan dengan menempuh perjalanan sejauh 2 km sampai menuju desa kenteng, kemudian sampailah Basecamp Sawit yang merupakan base utama untuk mendaki puncak gunung andong ini.</value>
      <webElementGuid>b1a263cf-8c94-4da3-82a7-9bf4a2092940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.wahidari.pendaki</value>
      <webElementGuid>386e36ae-bc11-4a3a-82b9-98bf7ce1c20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>41fc7b9d-abda-48ce-a637-483f9d1268ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb667e4d-d80c-4c96-891d-f44c78cc33d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69da5760-9aeb-4685-8458-1ef01fde492c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44893dc5-cdfb-4090-bc89-ce7bafb7694b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>adb20228-1c39-40c2-bc5e-a7c8c7dbd4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>456d8f44-3568-4b9c-993f-9940b306bb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>44ea4eab-cfe1-49eb-b470-eb13c822292d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bfce31d5-1d5a-470d-9d5c-93e2a18ebed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8fc784b9-0f62-4c88-8d14-30fbf18c0ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5349e18-3d5e-414d-96e2-e2c4b7283c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>f71d3d38-b740-48d6-b6b2-237766f2f4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>792</value>
      <webElementGuid>07cc409c-6d75-4fb1-9c14-4a303e8fa0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1020</value>
      <webElementGuid>fd1d283f-188e-462d-980f-bcf87983838a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>591</value>
      <webElementGuid>f9d2320f-9206-432c-b52c-44da884c2155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[30,792][1050,1383]</value>
      <webElementGuid>51a50793-6123-4d96-95ed-137d630f005a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a43ebfb4-9f58-4236-b803-a4e757f95523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[4]/android.widget.TextView[1]</value>
      <webElementGuid>d528cc15-d4a1-49c9-abfe-a09471723b51</webElementGuid>
   </webElementProperties>
   <locator>//*[@class = 'android.widget.TextView' and (@text = 'Selain melewati jalur barat, rute alternatif dalam melakukan pendakian menuju puncak gunung andong juga bisa dimulai dari jalur utara yaitu dari semaran menuju solo kemudian transit ke pasar sapi salatgiga, nah dari sini anda bisa menuruskan perjalanan ke pasar ngablak, dari pasar ngablak anda bisa meneruskan perjalanan dengan menempuh perjalanan sejauh 2 km sampai menuju desa kenteng, kemudian sampailah Basecamp Sawit yang merupakan base utama untuk mendaki puncak gunung andong ini.' or . = 'Selain melewati jalur barat, rute alternatif dalam melakukan pendakian menuju puncak gunung andong juga bisa dimulai dari jalur utara yaitu dari semaran menuju solo kemudian transit ke pasar sapi salatgiga, nah dari sini anda bisa menuruskan perjalanan ke pasar ngablak, dari pasar ngablak anda bisa meneruskan perjalanan dengan menempuh perjalanan sejauh 2 km sampai menuju desa kenteng, kemudian sampailah Basecamp Sawit yang merupakan base utama untuk mendaki puncak gunung andong ini.')]</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
