<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>Gunung Guntur Deskripsi</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>d2dcc549-2cb7-4a9d-88d1-ee07708043ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b91f1b13-0f4e-4556-94e7-fbec1699b7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Selain Gunung Papandayan dan Cikuray, Gunung lain di Garut yang juga menjadi kesukaan pendaki di Jawa Barat dan sekitarnya adalah Gunung Guntur. Gunung ini memiliki ketinggian 2.249 mdpl dan punya pemandangan yang tak kalah indah dengan gunung-gunung lainnya.
     Walau tingginya tidak sampai 3.000 mdpl, namun pendakian ke gunung ini terkenal cukup sulit karna medan yang terjal serta tidak adanya jalur khusus menuju ke puncak. Apalagi jika cuaca sedang berkabut, track pendakian akan semakin menyulitkan para pendaki. Namun, apa yang akan kita dapatkan begitu sampai di puncak sangatlah spektakuler.</value>
      <webElementGuid>e47d166b-5d4c-487b-878c-1ed62d517497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>com.wahidari.pendaki:id/detail_gunung</value>
      <webElementGuid>ee5e1119-e387-4b87-8d31-cd6aeb3ee7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.wahidari.pendaki</value>
      <webElementGuid>c1b5789c-e872-4141-8ea9-8b21705d283e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5577c50-ffcc-4904-8acd-0a35faf7c042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d6cf9bc-fe83-4404-8ed4-17c89ad1d315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>805ffe21-c637-4158-9956-025cea6c8317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c7febc5-d013-4198-acb0-6663bfd2016e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>94460292-4a0b-4176-91ce-c40068fb41ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b9d400d-bd8f-42e8-9ef3-572341add5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b9abb085-30f9-456c-9a95-c90ffd248c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e0cc3b07-d3d4-493b-bd63-7edd0bfddc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e6cc2b6-a697-4e2c-aec5-96575a6dc5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>adc84763-ba46-4178-806e-271230b87a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>c2b2c4cd-f0e4-43be-b044-0731fbc11047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>901</value>
      <webElementGuid>9c8ccebb-617c-4a91-8778-fc771e8b8587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1008</value>
      <webElementGuid>1c76c198-2eb0-487a-aecd-8667309cfa46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>863</value>
      <webElementGuid>9c248ff3-c0a0-4f07-8278-ac98f967535b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[36,901][1044,1764]</value>
      <webElementGuid>6ae168fc-0e93-463d-8c26-5b434f76bf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f59a94d-f7b2-4e18-b7a3-b64a6e6b7b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.TextView[2]</value>
      <webElementGuid>602ba416-d2a4-4c64-9826-aca097d26277</webElementGuid>
   </webElementProperties>
   <locator>//*[@class = 'android.widget.TextView' and (@text = '     Selain Gunung Papandayan dan Cikuray, Gunung lain di Garut yang juga menjadi kesukaan pendaki di Jawa Barat dan sekitarnya adalah Gunung Guntur. Gunung ini memiliki ketinggian 2.249 mdpl dan punya pemandangan yang tak kalah indah dengan gunung-gunung lainnya.
     Walau tingginya tidak sampai 3.000 mdpl, namun pendakian ke gunung ini terkenal cukup sulit karna medan yang terjal serta tidak adanya jalur khusus menuju ke puncak. Apalagi jika cuaca sedang berkabut, track pendakian akan semakin menyulitkan para pendaki. Namun, apa yang akan kita dapatkan begitu sampai di puncak sangatlah spektakuler.' or . = '     Selain Gunung Papandayan dan Cikuray, Gunung lain di Garut yang juga menjadi kesukaan pendaki di Jawa Barat dan sekitarnya adalah Gunung Guntur. Gunung ini memiliki ketinggian 2.249 mdpl dan punya pemandangan yang tak kalah indah dengan gunung-gunung lainnya.
     Walau tingginya tidak sampai 3.000 mdpl, namun pendakian ke gunung ini terkenal cukup sulit karna medan yang terjal serta tidak adanya jalur khusus menuju ke puncak. Apalagi jika cuaca sedang berkabut, track pendakian akan semakin menyulitkan para pendaki. Namun, apa yang akan kita dapatkan begitu sampai di puncak sangatlah spektakuler.') and @resource-id = 'com.wahidari.pendaki:id/detail_gunung']</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
